//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class SudokuSolver
	{
		int[,] test_grid = 
		{
			{ 1, 8, 4, 9, 6, 3, 7, 2, 5 },
			{ 5, 6, 2, 7, 4, 8, 3, 1, 9 },
			{ 3, 9, 7, 5, 1, 2, 8, 6, 4 },
			{ 2, 3, 9, 6, 5, 7, 1, 4, 8 },
			{ 7, 5, 6, 1, 8, 4, 2, 9, 3 },
			{ 4, 1, 8, 2, 3, 9, 6, 5, 7 },
			{ 9, 4, 1, 3, 7, 6, 5, 8, 2 },
			{ 6, 2, 3, 8, 9, 5, 4, 7, 1 },
			{ 8, 7, 5, 4, 2, 1, 9, 3, 6 } 
		};
		
		public bool IsLegalSudokuGrid(int[,] test_grid)
		{
			// check all rows == 45
			// check all columns == 45
			// check all 3x3 grids == 45
			for(i = 
			
			// your code goes here
			return true;
		}
		
//		public SudokuSolver ()
//		{
//		}
	}
}

